dataset<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE)
feb12<-subset(dataset,Date=="1/2/2007"|Date=="2/2/2007")
feb12$Date<-as.Date(feb12$Date)
feb12$Time<-strptime(feb12$Time,"hh:mm:ss")
feb12$Global_active_power<-as.numeric(feb12$Global_active_power)
feb12$Global_reactive_power<-as.numeric(feb12$Global_reactive_power)
feb12$Voltage<-as.numeric(feb12$Voltage)
feb12$Global_intensity<-as.numeric(feb12$Global_intensity)
feb12$Sub_metering_1<-as.numeric(feb12$Sub_metering_1)
feb12$Sub_metering_2<-as.numeric(feb12$Sub_metering_2)
feb12$Sub_metering_3<-as.numeric(feb12$Sub_metering_3)
png("plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(feb12$Global_active_power,type="n",xaxt="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(feb12$Global_active_power)
axis(1,at=c(0,1500,2500),labels=c("Thu","Fri","Sat"))
plot(feb12$Sub_metering_1,type="n",yaxt="n",xaxt="n",xlab="",ylab="Energy sub metering")
axis(2,at=c(0,10,20,30),labels=c(0,10,20,30))
axis(1,at=c(0,1500,2500),labels=c("Thu","Fri","Sat"))
lines(feb12$Sub_metering_1)
lines(feb12$Sub_metering_2,col="red")
lines(feb12$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,cex=1 )
plot(feb12$Voltage,type="n",xlab="datetime",ylab="Voltage",xaxt="n")
lines(feb12$Voltage)
axis(1,at=c(0,1500,2500),labels=c("Thu","Fri","Sat"))
plot(feb12$Global_reactive_power,type="n",xlab="datetime",ylab="Global_reactive_power",xaxt="n")
lines(feb12$Global_reactive_power)
axis(1,at=c(0,1500,2500),labels=c("Thu","Fri","Sat"))
dev.off()

