dataset<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE)
feb12<-subset(dataset,Date=="1/2/2007"|Date=="2/2/2007")
feb12$Date<-as.Date(feb12$Date)
feb12$Time<-strptime(feb12$Time,"hh:mm:ss")
feb12$Global_active_power<-as.numeric(feb12$Global_active_power)
png("plot2.png",width=480,height=480)
plot(feb12$Global_active_power,type="n",xaxt="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(feb12$Global_active_power)
axis(1,at=c(0,1500,2500),labels=c("Thu","Fri","Sat"))
dev.off()